# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import signals_pb2 as TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in TinvestPy/TinvestPy/grpc/signals_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignalServiceStub(object):
    """Сервис для получения технических сигналов и мнений аналитиков по инструментам.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategies = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.SignalService/GetStrategies',
                request_serializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesRequest.SerializeToString,
                response_deserializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesResponse.FromString,
                _registered_method=True)
        self.GetSignals = channel.unary_unary(
                '/tinkoff.public.invest.api.contract.v1.SignalService/GetSignals',
                request_serializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsRequest.SerializeToString,
                response_deserializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsResponse.FromString,
                _registered_method=True)


class SignalServiceServicer(object):
    """Сервис для получения технических сигналов и мнений аналитиков по инструментам.
    """

    def GetStrategies(self, request, context):
        """GetStrategies — стратегии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignals(self, request, context):
        """GetSignals — сигналы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategies,
                    request_deserializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesRequest.FromString,
                    response_serializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesResponse.SerializeToString,
            ),
            'GetSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignals,
                    request_deserializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsRequest.FromString,
                    response_serializer=TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tinkoff.public.invest.api.contract.v1.SignalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tinkoff.public.invest.api.contract.v1.SignalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignalService(object):
    """Сервис для получения технических сигналов и мнений аналитиков по инструментам.
    """

    @staticmethod
    def GetStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.SignalService/GetStrategies',
            TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesRequest.SerializeToString,
            TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tinkoff.public.invest.api.contract.v1.SignalService/GetSignals',
            TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsRequest.SerializeToString,
            TinvestPy_dot_TinvestPy_dot_grpc_dot_signals__pb2.GetSignalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
